
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8002
    compression:
      enabled: true
      mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/javascript,application/javascript,text/css


# mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/images?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

swagger2:
    enable: true

file:
  uploadAddr: "D:/images/"
#file:
#  uploadFolder: "/root/uploadFiles/"

#mybatis-plus
mybatis-plus:

  typeAliasesPackage: top.wanmudong.images.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: -1
    #logic-not-delete-value: 0
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
#    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:

    map-underscore-to-camel-case: true
    cache-enabled: false
    #call-setters-on-nulls: true
    aggressive-lazy-loading: false
    lazy-loading-enabled: true
    default-executor-type: reuse

  mapper-locations: classpath:mapper/images/*Mapper.xml

    #return-instance-for-empty-row: true
